# Generated by Django 3.2.7 on 2021-09-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankledger',
            old_name='bank_person',
            new_name='bank',
        ),
    ]
