# Generated by Django 3.0 on 2021-09-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedcustomers',
            name='category',
        ),
    ]
