# Generated by Django 3.0 on 2021-09-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20210920_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='partyorder',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='partyorder',
            name='rate',
        ),
        migrations.CreateModel(
            name='PartyOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('party_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.PartyOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Product')),
            ],
        ),
    ]
