# Generated by Django 3.0 on 2021-09-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20210920_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyorder',
            name='total_amount',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
