# Generated by Django 3.2.6 on 2021-09-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20210908_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyorder',
            name='dl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.discountledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='fl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.freightledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.salesledger'),
        ),
    ]
