# Generated by Django 3.2.6 on 2021-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20210906_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyorder',
            name='discounted_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
