# Generated by Django 3.2.6 on 2021-09-08 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_partyorder_discounted_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('account_no', models.CharField(max_length=400)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CashPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClearingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FreightPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='partyledger',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='dl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.partyledger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='fl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.partyledger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='freight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='apis.partyledger'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Clearing', 'Clearing')], default='Cash', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recovery',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.salesofficerledger'),
        ),
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('qty', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.salesperson')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.CreateModel(
            name='FreightLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('qty', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('freight_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.freightperson')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.CreateModel(
            name='DiscountLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('discounted_amount', models.FloatField()),
                ('qty', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('discount_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.discountperson')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.CreateModel(
            name='ClearingLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('clearing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.clearingperson')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('cash_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.cashperson')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.ledger')),
                ('bank_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.bank')),
            ],
            bases=('apis.ledger',),
        ),
        migrations.AddField(
            model_name='recovery',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.bank'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='bl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.bankledger'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='cl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.cashledger'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='cll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.clearingledger'),
        ),
    ]
